config/routes.rb
Rails.application.routes.draw do
  resources :flowers
  root 'flowers#index'
  resources :cart do
  member do
    get 'cart'
  end
end

  devise_for :users
  

  get 'uploader/image'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flower.rb
class Flower < ActiveRecord::Base
	belongs_to :cart
	mount_uploader :image, ImageUploader
	validates_processing_of :image
  validate :image_size_validation
 
  private
  
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :flowers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add
    id = params[:id]
    if session[:cart] then
      cart = session[:cart]
    else
      session[:cart] = {}
      cart = session[:cart]
    end
    if cart[id] then
      cart[id] = cart[id] +1
    else
      cart[id]=1
    end
    redirect_to :action => :index
  end
  def clearCart
    session[:cart]=nil
    redirect_to :action => :index
  end

  def index
  	if session[:cart] then
  		@cart=session[:cart]
  	else
  		@cart ={}
  	end
  end
  def show
    @flower=Flower.find(params[:id])
  end
  def destroy
    @flower = Flower.find(params[:id])
    @flower.destroy
    redirect_to flowers_path
  end
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
	before_filter :authenticate_user!, :except => [:show, :index]
  # http_basic_authenticate_with email: "gopi@gmail.com", password: "gopiraju", except: [:index, :show]
  def index
  	@flowers=Flower.all
     # render json: @flowers
     # @order_item = current_order.order_items.new
  end

  def show
  	@flower=Flower.find(params[:id])
  end
  

  def new
  	@flower=Flower.new
  end

  def edit
  	@flower=Flower.find(params[:id])
  end

  def create
		@flower=Flower.new(flower_params)
		if @flower.save
			redirect_to @flower
	   	else
	   	render 'new'
		end
	end

  def update
		@flower=Flower.find(params[:id])
		if @flower.update(flower_params)
			redirect_to @flower
		  else
			render 'edit'
		end
	end

  def destroy
    @flower = Flower.find(params[:id])
    @flower.destroy
 		redirect_to flowers_path
  end

	private

  def flower_params
    params.require(:flower).permit(:name, :description, :image, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/uploader_helper.rb
module UploaderHelper
end

app/views/cart/index.html.erb
<h1>Your Cart</h1>

  <% @cart.each do |id| %>
  <% @flower = Flower.find_by_id(id) %>
   <% total =0 %>
    <div class="col-md-12">
	<p>
	  <strong>Name:</strong>
	  <%= @flower.name %>
	</p> 
	<p>
	  <strong>Description:</strong>
	  <%= @flower.description %>
	</p> 
	<p>
	  <strong>ImagePrice: </strong>
	  <%= @flower.price %>
	  <%= image_tag @flower.image, class: "thumbnail" %>
	</p> 
 
  <% end %>
  <%= link_to 'Back', flowers_path, class: "btn btn-default"%>
  </div>

app/views/cart/show.html.erb
<div class="col-md-12">
	<p>
	  <strong>Name:</strong>
	  <%= @flower.name %>
	</p> 
	<p>
	  <strong>Description:</strong>
	  <%= @flower.description %>
	</p> 
	<p>
	  <strong>ImagePrice: </strong>
	  <%= @flower.price %>
	  <%= image_tag @flower.image, class: "thumbnail" %>
	</p> 
	<span><%= link_to 'Back', flowers_path, class: "btn btn-default"%></span>
	<span><%= link_to 'Empty Cart', cart_path, class: "btn btn-default"%> </span>
</div>

app/views/flowers/_carousel.html.erb
<div class="col-md-12 caurosel">
  <div id="mycarousel" class="carousel slide" data-ride="carousel" data-interval="5000">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= image_tag "flowers-banner.jpg", class: "tales" %>
      </div>
      <div class="item">
        <%= image_tag "gul5.jpg", class: "tales" %>
      </div>
      <div class="item">
        <%= image_tag "rose.jpg", class: "tales" %>
      </div>
      <div class="item">
        <%= image_tag "sunflower.jpg", class: "tales" %>
      </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#mycarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#mycarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/flowers/_form.html.erb
<%= form_for @flower, html: { multipart: true } do |f| %>
  <% if @flower.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@flower.errors.count, "error") %> prohibited this pet from being saved:
      </h2> 
      <ul>
        <% @flower.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="actions">
    <% if @flower.new_record? %>
      <%= f.submit 'Create', :class => 'btn btn-default' %>
    <% else %>
      <%= f.submit 'Update', :class => 'btn btn-default' %>
    <% end %>
    <%= link_to 'Back', flowers_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/flowers/edit.html.erb
<div class="col-md-offset-3 col-md-6 well well-top">
	<h1>Editng List</h1>
	<%= render 'form'%> 
</div>

app/views/flowers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <%= render 'carousel' %>
</div>
    <% @flowers.each do |flower| %>
    <div class="col-md-3 flower-gape">
      <div class="thumbnail">
        <div><img src="<%= flower.image %>" class="img-responsive center-block"></div>
        <div>
          <span><%= flower.name %></span>
        </div>
        <div>
          <span>price : <%= flower.price %></span>
        </div>
        
          <span><%= link_to 'View', flower_path(flower), class: "btn btn-default btn-sm" %></span>
          <span><%= link_to 'Edit', edit_flower_path(flower), class: "btn btn-default btn-sm" %></span>
          <span><%= link_to 'Destroy', flower, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-default btn-sm" %></span>
       
      </div>
    </div>
    <% end %>
<div class="new"><%= link_to 'New Flower', new_flower_path, class: "btn btn-default btn" %></div>

app/views/flowers/new.html.erb
<div class="col-md-offset-3 col-md-6 well well-top">
	<h1>New Flower</h1>
	<%= render 'form' %>
</div>

app/views/flowers/show.html.erb
<div class="col-md-12">
	<p>
	  <strong>Name:</strong>
	  <%= @flower.name %>
	</p> 
	<p>
	  <strong>Description:</strong>
	  <%= @flower.description %>
	</p> 
	<p>
	  <strong>ImagePrice: </strong>
	  <%= @flower.price %>
	  <%= image_tag @flower.image, class: "thumbnail" %>
	</p> 
	<%= link_to 'Edit', edit_flower_path(@flower), class: "btn btn-default" %>
	<%= link_to 'Back', flowers_path, class: "btn btn-default"%>
	<%= link_to 'Add to cart', cart_path, class: "btn btn-default"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Myflowers</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	  <nav class="navbar navbar-inverse logo" style="margin:0px; border-radius: 0px;">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header ">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand header" href="/">FlowerShop</a>
		    </div>
	      <div class="nav navbar-nav navbar-right sign_in">
          <span><% if user_signed_in? %>
          signed in as <%= current_user.email %> 
          not you?<%= link_to "SignOut", destroy_user_session_path, :method => :delete%></span>
         <% else %>
         <span>
         <%= link_to "SignUp",new_user_registration_path %>
         <%= link_to "SignIn", new_user_session_path %>
         
         </span>
          <% end %>
	      </div>
		  </div><!-- /.container-fluid -->
		</nav>

		<div class="container">
			<%= yield %>
		</div>
		<nav class="footer navbar navbar-inverse">
        <div class="container">
          <h3>copyright@2016</h3>
        </div>
      </nav>
	</body>
</html>